version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: automation4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  backend:
    build: ./cockpit-main
    container_name: corelatest-container
    restart: on-failure
    ports:
      - "9082:9082"
    environment:
      DB_HOST: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: automation4
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/automation4?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - my-network

  nodeapi:
    build:
      context: ./nodeapi
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - my-network

  angular:
    build:
      context: ./angularCRUD
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - nodeapi
    restart: on-failure
    networks:
      - my-network

  dotnet:
    build:
      context: ./dotnetapi/WebApplication2
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - angular
    restart: on-failure
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:

